### ISSUE TITLE
Sync folder times?

### ISSUE THREAD

**Issue by avindra** [tst2005/git-timesync#2]
How difficult would it be to sync folder times as well?

My understanding is that git doesnt really think about folders too much-- that it really cares about the files. So in order to sync folder times, you'd have to recurse through the entire tree and pull up the last mod times and put them on the folders.

Would it be difficult to implement? Having the correct file times is nice, but the folders can still  be out of sync.

**Comment by avindra** [comment]
Looks like this ZSH script does it:

``` zsh
for d (**/*(D/)) touch -r $d/*(D.om[1]) -- $d
```

source: http://unix.stackexchange.com/a/86682/63602

**Comment by diranged** [comment]
:+1: this is an issue that should be solved, as it will help with Dockerfiles that add entire directories (`ADD resources/ ...`).

**Comment by tst2005** [comment]
Hello guys,

git does not manage information about directories.
I make some experimentation about (built-in) ways to search and get information inside a directory...
to be continue...

**Comment by billward** [comment]
i agree this would be a nice feature - how about just setting the directory timestamp to match the newest of the things in that directory? It should be done recursively so that the top level will be given the date of the newest thing anywhere in that directory. Perhaps this would be done only with an option such as -d

**Comment by tst2005** [comment]
Yes, I will try to finalized this feature soon.
I remember I made (somewhere) a find-like function made only with POSIX built-in that should help...

**Comment by billward** [comment]
I think writing your own recursive shell function is the way to go. in pseudocode:
- call itself on each subdirectory
- find newest timestamp in current folder
- update timestamp of folder

**Comment by avindra** [comment]
i'm going to close this, and let me say, the mod times on directories never made sense to me!  i could never concretely determine the interactions that govern changes to it
